// <auto-generated />
using System;
using Kitakun.VkModules.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Kitakun.VkModules.Persistance.Migrations
{
    [DbContext(typeof(VkDbContext))]
    [Migration("20191018101145_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Kitakun.VkModules.Core.Domain.DataCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CalculationStartedAt");

                    b.Property<DateTime>("From");

                    b.Property<string>("JsonValue")
                        .HasColumnType("json");

                    b.Property<long>("OwnerExternalId");

                    b.Property<DateTime>("To");

                    b.Property<byte>("Type");

                    b.HasKey("Id");

                    b.ToTable("DataCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
